name: Python FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      API_KEY: ${{ secrets.API_KEY }}
      ENV: "staging"

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app main.py --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Run Unit Tests
        run: python -m unittest discover tests

      - name: Show Env/Secret
        run: |
          echo "Environment: $ENV"
          echo "API Key Exists? ${{ secrets.API_KEY != '' }}"
